# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "4.4.5"

default_platform :ios
xcode_version = '8.3.3'
app_version = '1.0'

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #carthage
  end



  desc "Install the xcode_version used"
  lane :install_xcode do
    xcode_install(version: xcode_version)
  end

  desc "Clean builds, simulators"
  lane :clean do
    reset_simulators
    xcclean(scheme:"MusicForThought")
    clean_build_artifacts
  end

  desc "Runs all the tests"
  lane :test do
    gym(scheme:"MusicForThought", workspace:"MusicForThought.xcworkspace", use_legacy_build_api:false)
    scan(scheme:"MusicForThought",device:"iPhone 7")
    xcov(scheme: "MusicForThought", minimum_coverage_percentage: 20.0)
  end

  desc "Build artifact"
  lane :build_artifact do
  gym(scheme: "MuiscForThought", workspace: "MusicForThought.xcworkspace")
  end

  desc "Builds development target and uploads to HockeyApp"
  lane :beta do
       gym(
      # enable_automatic_code_signing(path:"MusicForThought"),
        workspace: "MusicForThought.xcworkspace",
        configuration: "beta",
        scheme: "MusicForThought",
        silent: true,
        clean: true,
        export_method: "development"
      )
      hockey(
          api_token: "2f368357f1aa44a5aed91b8fcb1b8f98",
        public_identifier: "eeefc50cf6a84b0786f7f5833d9bff4a",
           bundle_version: "1.0",
        notify: '0',
      )
    end



  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
